version: "3.8"
services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mastra_vectors
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=200'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
